### ISSUE TITLE
IIncorrect format at line 176 for sample stacked_var.perf

### ISSUE THREAD

**Issue by JianpingZeng** [derekbruening/bargraph#39]
Hi,
I have tested the latest release version and version 4.7. The file generated by bargraph is mal-formed 
and have some extra newlines leading from line 176 for compiling stacked_var.perf.

After removing those redundant newlines, it works properly. So maybe it is a bug that.
I use the following command to generate desired temporary file (stacked_var.dat) for 
checking where that bug occurs.

bargraph stacked_var.perf > stacked_var.dat

I use Ubuntu 16.4 with gnu 5.0.7.

**Comment by JianpingZeng** [comment]
And fig2dev is version 3.2.5e

**Comment by BorisPis** [comment]
Same issue here

**Comment by BorisPis** [comment]
Using a newer fig2dev (Version 3.2.6a) solved the issue for me

**Comment by JianpingZeng** [comment]
OK, thank you!
